"""Add role to users table

Revision ID: 956fa0efe19c
Revises: 7de02cdd3a10
Create Date: 2026-07-26 13:41:47.392267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '956fa0efe19c'
down_revision: Union[str, Sequence[str], None] = '7de02cdd3a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(

        'users',
        sa.Column(

            'role',
            sa.String(length=20),
            nullable=False,
            server_default='user'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
